server.port=8080
spring.application.name=simple-vcs

spring.datasource.url=jdbc:mysql://localhost:3306/simple_vcs_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto = create-drop
# tova trqbva da se runne parviq pat kato nqkoi vzima ot securite i login commita main, poneje ima razlika v versiite, posle da se varne na gornoto s update



spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
